# Generated by Django 5.1 on 2024-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_product_summary_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
