# Generated by Django 5.1 on 2024-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(default="This is cool!"),
        ),
    ]
