# Generated by Django 5.1 on 2024-08-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0004_remove_product_price_alter_product_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=10),
            preserve_default=False,
        ),
    ]
