# Generated by Django 5.1 on 2024-08-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0007_rename_featured_product_feature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="feature",
            new_name="featured",
        ),
    ]
