# Generated by Django 5.1 on 2024-08-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0008_rename_feature_product_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="featured",
        ),
    ]
