# Generated by Django 5.1 on 2024-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0010_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(),
        ),
    ]
